language: python

env:
  - CASSANDRA_VERSION=21 TOX_ENV=py27
  - CASSANDRA_VERSION=21 TOX_ENV=py34

before_install:
  - sudo echo "deb http://www.apache.org/dist/cassandra/debian ${CASSANDRA_VERSION}x main" | sudo tee -a /etc/apt/sources.list
  - sudo echo "deb-src http://www.apache.org/dist/cassandra/debian ${CASSANDRA_VERSION}x main" | sudo tee -a /etc/apt/sources.list
  - sudo rm -r ~/.gnupg/gpg.conf
  - sudo gpg --keyserver pgp.mit.edu --recv-keys F758CE318D77295D
  - sudo gpg --export --armor F758CE318D77295D | sudo apt-key add -
  - sudo gpg --keyserver pgp.mit.edu --recv-keys 2B5C1B00
  - sudo gpg --export --armor 2B5C1B00 | sudo apt-key add -
  - sudo gpg --keyserver pgp.mit.edu --recv-keys 0353B12C
  - sudo gpg --export --armor 0353B12C | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y cassandra
  - sudo rm -rf /var/lib/cassandra/*
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /etc/cassandra/cassandra-env.sh"
  - sudo service cassandra start

# TODO: Need to improve this somehow (Cassandra has delay on start...)
before_script: sleep 10

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
